GTI_Solutionx/GTI_Solutionx/Models/Dashboard/AzImporter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GTI_Solutionx.Models.Dashboard
{
    public class AzImporter
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ItemID { get; set; }

        public string Sku { get; set; }

        public string Category { get; set; }

        public string ItemName { get; set; }

        public string Image1 { get; set; }

        public string Image2 { get; set; }

        public string Image3 { get; set; }

        public string Image4 { get; set; }

        public string Image5 { get; set; }

        public string Image6 { get; set; }

        public string Image7 { get; set; }

        public string Image8 { get; set; }

        public string MainImage { get; set; }

        public double WholeSale { get; set; }

        public int Quantity { get; set; }

        public int Weight { get; set; }

        public string HTMLDescription { get; set; }

        public string ShortDescription { get; set; }
        
    }
}

GTI_Solutionx/GTI_Solutionx/Models/Dashboard/Shipping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GTI_Solutionx.Models.Dashboard
{
    public class Shipping
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int weightId { get; set; }
        public double ItemPrice { get; set; }
        
    }
}

GTI_Solutionx/GTI_Solutionx/Controllers/AzImporterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;
using DatabaseModifier;
using EFCore.BulkExtensions;
using GTI_Solutionx.Data;
using GTI_Solutionx.Models.Dashboard;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GTI_Solutions.Controllers
{
    public class AzImporterController : Controller
    {
        public ApplicationDbContext _context;

        public AzImporterController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            ViewBag.TimeStamp = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .LastOrDefault()?.TimeStamp.ToString("dd/MM/yyyy HH:mm tt");

            ViewBag.type = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .LastOrDefault()?.type;

            ViewBag.Wholesalers = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .LastOrDefault()?.Wholesalers;

            Guid guid = Guid.NewGuid();

            ViewBag.ExcelGuid = guid.ToString();

            return View(_context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .OrderByDescending(x => x.TimeStamp).Take(5).ToList());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Shipping()
        {
            return View(_context.Shipping);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string file)
        {
            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file + ".xlsx");
            try
            {
                var azImportItems = _context.Wholesaler_AzImporter.ToDictionary(x => x.Sku, y => y);

                foreach (var az in azImportItems)
                {
                    az.Value.Quantity = 0;
                }

                DBModifierAzImporterExcel AzImporter = new DBModifierAzImporterExcel(path, azImportItems);

                AzImporter.TableExecutor();

                // delete everything from the db, then update

                using (var tran = _context.Database.BeginTransaction())
                {
                    await _context.BulkDeleteAsync(_context.Wholesaler_AzImporter.ToList());
                    tran.Commit();
                }

                using (var tran = _context.Database.BeginTransaction())
                {
                    await _context.BulkInsertOrUpdateAsync(AzImporter.azImport);
                    tran.Commit();
                }

                ServiceTimeStamp service = new ServiceTimeStamp();

                service.TimeStamp = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow
                        , TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));

                service.Wholesalers = Wholesalers.AzImporter.ToString();

                service.type = "Excel";

                _context.ServiceTimeStamp.Add(service);

                _context.SaveChanges();

            }
            catch(Exception e)
            {
                SetUIValues(path);

                ViewData["Error"] = e.Message.ToString();

                return View(_context.ServiceTimeStamp
                            .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                                .OrderByDescending(x => x.TimeStamp).Take(5).ToList());
            }

            SetUIValues(path);

            ViewData["Success"] = "Database updated successfully at " + TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow
                    , TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));

            return View(_context.ServiceTimeStamp
                        .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                            .OrderByDescending(x => x.TimeStamp).Take(5).ToList());
        }

        private void SetUIValues(string path)
        {
            System.IO.File.Delete(path);

            ViewBag.TimeStamp = _context.ServiceTimeStamp
            .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
            .LastOrDefault()?.TimeStamp.ToString("dd/MM/yyyy HH:mm tt");

            ViewBag.type = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .LastOrDefault()?.type;

            ViewBag.Wholesalers = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.AzImporter.ToString())
                .LastOrDefault()?.Wholesalers;
        }

        [HttpPost]
        public Task<IActionResult> UpdateAzImports()
        {
            //var client = new System.Net.WebClient();
            string url = @"http://www.azimporter.com/datafeed/dailydatafeed2.csv";
            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot", "test.csv");

            //client.DownloadFile(url, path);

            var memory = new MemoryStream();

            using (var client = new WebClient())
            {
                var content = client.DownloadData(url);

                string csvDocument = Encoding.ASCII.GetString(content);

                var file = new FileInfo(path);

                using (FileStream fs = file.Create())
                {
                    //Add some information to the file.
                    fs.Write(content, 0, csvDocument.Length);
                }

                var lines = System.IO.File.ReadAllLines(path, Encoding.UTF8).Select(a => a.Split(','));

                List<Wholesaler_AzImporter> items = new List<Wholesaler_AzImporter>();
                int skipFirst = 1;

                foreach (var line in lines)
                {    
                    if (line.Length == 17)
                    {
                        int curr = 1;
                        Wholesaler_AzImporter azImporter = new Wholesaler_AzImporter();
                        foreach (var col in line)
                        {
                            // skip the first line because it is the title of the csv file
                            if (skipFirst == 1)
                                break;
                            // The first item is always the sku
                            if(curr == 1)
                            {
                                azImporter.Sku = col.Replace('"', ' ');
                            }
                            // loop until the first lines contains HTTP

                            // Once it does not have HTTP and it can be converted into a double
                            // we have the wholesale

                            // The next should the quantity and it can be turned into an integer

                            // Add the azImporter to the list
                            if (curr == 17)
                            {
                                items.Add(azImporter);
                            }

                            curr++;
                        }
                        skipFirst++;
                    }
                }

                //List<AzImporter> items = new List<AzImporter>();
                //int fieldCount = 0;
                //string[] headers;

                //using (TextFieldParser parser = new TextFieldParser(@"c:\temp\test.csv"))
                //{
                //    parser.TextFieldType = FieldType.Delimited;
                //    parser.SetDelimiters(",");
                //    while (!parser.EndOfData)
                //    {
                //        //Process row
                //        string[] fields = parser.ReadFields();
                //        foreach (string field in fields)
                //        {
                //            //TODO: Process field
                //        }
                //    }
                //}

                //using (CsvReader csv =  new CsvReader(file.OpenText()))
                //{
                //    fieldCount = csv.FieldCount;

                //    headers = csv.GetFieldHeaders();
                //    while (csv.ReadNextRecord())
                //    {
                //        for (int i = 0; i < fieldCount; i++)
                //            Console.Write(string.Format("{0} = {1};",
                //                          headers[i], csv[i]));
                //        Console.WriteLine();
                //    }
                //}

                using (var workbook = new XLWorkbook())
                {
                    //rowCount = 1;
                    Wholesaler_AzImporter azImporter = new Wholesaler_AzImporter();
                    //foreach (var line in csv.GetRecords<AzImporter>())
                    //{


                    //    colCount = 1;
                    //    //foreach (var col in line)
                    //    //{
                    //    //    if (rowCount != 1)
                    //    //    {
                    //    //        if(colCount == 1)
                    //    //        {
                    //    //            azImporter.Sku = col.Replace('"', ' ');
                    //    //        }
                    //    //        else if(colCount == 2)
                    //    //        {
                    //    //            azImporter.Category = col.Replace('"', ' ');
                    //    //        }
                    //    //        else if (colCount == 3)
                    //    //        {
                    //    //            azImporter.ItemName = col.Replace('"', ' ');
                    //    //        }
                    //    //        else if (colCount == 4)

GTI_Solutionx/GTI_Solutionx/Views/AzImporter/Index.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.ServiceTimeStamp>
@{
    ViewBag.Title = "AzImport Update";
}

<head>
    <!-- DataTables -->
    <link href="~/assets/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
</head>
<div class="wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12">
                <div class="card ">
                    <div class="card-body">
                        <h2>AzImport Inventory Excel Importer</h2>

                        <p>
                            This application is intended to create an excel which will
                            be able to take an excel from an Amazon report and return
                            the items that are available in a spreadsheet.
                        </p>
                        <div id="dropzone">
                            <form asp-controller="Home" asp-action="DropzoneFileUpload" asp-antiforgery="false"
                                  class="dropzone" id="myAwesomeDropzone" enctype="multipart/form-data">
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control" name="fileName" value="@ViewBag.ExcelGuid">
                                </div>
                                <div class="fallback">
                                    Drop files here or click to upload.<br>
                                    <input name="file" type="file" />
                                </div>
                            </form>
                        </div>
                        <form asp-controller="AzImporter" asp-action="Index" asp-antiforgery="false"
                              enctype="multipart/form-data">
                            <input type="hidden" class="form-control" name="file" value="@ViewBag.ExcelGuid">
                            @if (@ViewData["Error"] != null)
                            {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>   
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                            </div>
                            }
                            @if (@ViewData["Success"] != null)
                            {
                            <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-checkbox-marked-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                            </div>
                            }
                            <div class="text-center m-t-15">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
        <p>
            Last <b>@ViewBag.Wholesalers</b> database update <b>@ViewBag.TimeStamp Updated via  @ViewBag.type</b> <br />
        </p>
        <div class="row">
            <div class="col-md-12">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th>Last Updated Date</th>
                                        <th>Database Update Type</th>
                                        <th>Wholesaler</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.TimeStamp.ToString("MM/dd/yyyy hh:mm tt")
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.type)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Wholesalers)
                                        </td>
                                    </tr>
                            }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GTI_Solutionx/GTI_Solutionx/Views/AzImporter/Shipping.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.Shipping>
@{
    ViewBag.Title = "AzImport Shipping";
}

<head>
    <!-- DataTables -->
    <link href="~/assets/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
</head>
<div class="wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="card ">
                    <div class="card-body">
                        <h2>AzImport Shipping</h2>

                        <p>
                            This application is intended to set up the AzImport
                            shipping prices.
                        </p>
                        <form asp-controller="AzImporter" asp-action="Shipping" asp-antiforgery="false"
                              enctype="multipart/form-data">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="ProfileUser">Weight:</label>
                                    <input type="number" class="form-control" name="Weight" placeholder="Weight" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="ProfileUser">Price:</label>
                                    <input type="text" class="form-control" name="Price" placeholder="Price" required>
                                </div>
                                <div class="form-group text-center col-md-12">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                </div>
                            </div>
                        </form>
                        @if (@ViewData["Error"] != null)
                        {
                        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>   
                            <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                        </div>
                        }
                        @if (@ViewData["Success"] != null)
                        {
                        <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <i class="mdi mdi-checkbox-marked-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                        </div>
                        }
                    </div>
                </div>
            </div> <!-- end col -->
            <div class="col-md-1">
            </div>
        </div> <!-- end row -->
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th>Weight in Lbs</th>
                                        <th>Price Per Item</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.weightId) lbs
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ItemPrice)
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1">
            </div>
        </div>
    </div>
</div>