GTI_Solutionx/GTI_Solutionx/Controllers/ShopifyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FrgxPublicApiSDK;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using ExcelModifier;
using DatabaseModifier;
using System.Collections.Concurrent;
using GTI_Solutionx.Data;
using GTI_Solutionx.Models.Dashboard;
using GTI_Solutionx.Code;
using Microsoft.AspNetCore.Authorization;
using EFCore.BulkExtensions;
using FrgxPublicApiSDK.Models;

namespace GTI_Solutionx.Controllers
{
    public class ShopifyController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ApplicationDbContext _context;
    
        public ShopifyController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        [Authorize(Roles = "Admin, user")]
        public IActionResult Index()
        {
            ViewBag.TimeStamp = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().TimeStamp.ToString("dd/MM/yyyy HH:mm tt");

            ViewBag.type = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().type;

            ViewBag.Wholesalers = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().Wholesalers;

            Guid guid = Guid.NewGuid();

            ViewBag.ExcelGuid = guid.ToString();
            
            var profile = new Profile();

            return View(_context.UsersList.Distinct().ToList());
        }

        [Authorize(Roles = "Admin, user")]
        public IActionResult Upload()
        {
            UploadUI();

            return View(_context.Profile.ToList());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Update()
        {
            return View(_context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .OrderByDescending(x => x.TimeStamp).Take(5).ToList());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult UpdateExcel()
        {
            Guid guid = Guid.NewGuid();

            ViewBag.ExcelGuid = guid.ToString();

            var test = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString());

            return View(_context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .OrderByDescending(x => x.TimeStamp).Take(5).ToList());
        }

        [Authorize(Roles = "Admin, user")]
        public IActionResult Delete()
        {
            return View(_context.UsersList.Distinct().ToList());
        }

        [Authorize(Roles = "Admin, user")]
        [HttpPost]
        public async Task<IActionResult> ProductExport(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return null;
            }

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file.FileName);
            
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            ServiceTimeStamp service = new ServiceTimeStamp();

            if (_context.ServiceTimeStamp.Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault<ServiceTimeStamp>() == null)
            {
                Helper.tablePreparer(path);

                service.TimeStamp = DateTime.Today;
                service.Wholesalers = Wholesalers.Fragrancex.ToString();
                _context.ServiceTimeStamp.Add(service);
                _context.SaveChanges();

            }
            else if(_context.ServiceTimeStamp.Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault<ServiceTimeStamp>().TimeStamp != DateTime.Today)
            {
                Helper.tablePreparer(path);
                service.Wholesalers = Wholesalers.Fragrancex.ToString();
                service.TimeStamp = DateTime.Today;
                _context.ServiceTimeStamp.Add(service);
                _context.SaveChanges();
            }

            var memory = new MemoryStream();

            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }

            memory.Position = 0;

            FileStreamResult returnFile =
                File(memory, Helper.GetContentType(path), Path.GetFileNameWithoutExtension(path)
                + "_Converted" + Path.GetExtension(path).ToLowerInvariant());

            System.IO.File.Delete(path);

            return returnFile;
        }
        
        [HttpPost]
        public IActionResult Upload(string file, string User, Profile profile2)
        {
            try
            {
                var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file + ".xlsx");

                Profile profile = _context.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == User).FirstOrDefault();

                var shopifyProfile = _context.ShopifyUser.ToDictionary(x => x.sku, x => x);
                var shopifyUsers = _context.UsersList.Where(x => x.userID == profile.ProfileUser)
                    .ToDictionary(x => x.sku, y => y.userID);

                ConcurrentDictionary<string, string> shopifyUsersConcurrent =
                    new ConcurrentDictionary<string, string>(shopifyUsers);

                ShopifyExcelCreator shopifyModifier =
                    new ShopifyExcelCreator(profile, shopifyProfile, shopifyUsersConcurrent, path);

                try
                {
                    shopifyModifier.ExcelGenerator();
                }
                catch (Exception e)
                {
                    System.IO.File.Delete(path);

                    throw e;
                }

                var builder = new ConfigurationBuilder()
                                     .SetBasePath(Directory.GetCurrentDirectory())
                                     .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                                     .AddEnvironmentVariables();

                IConfiguration Configuration;
                builder.AddEnvironmentVariables();
                Configuration = builder.Build();

                string connectionstring = Configuration.GetConnectionString("DefaultConnection");

                using (SqlConnection sourceConnection = new SqlConnection(connectionstring))
                {
                    sourceConnection.Open();
                    try
                    {
                        DBModifierShopifyUserList user =
                            new DBModifierShopifyUserList(shopifyModifier.shopifyUserTemp, profile);
                        user.TableExecutor();
                        // Execute raw query

                        var command = sourceConnection.CreateCommand();
                        command.CommandText = "exec MergeUsersList;";
                        command.Connection = sourceConnection;
                        command.ExecuteNonQuery();
                        sourceConnection.Close();

                    }
                    catch (Exception e)
                    {
                        sourceConnection.Close();
                        System.IO.File.Delete(path);
                        throw e;
                    }
                }
            }
            catch(Exception e)
            {
                ViewData["Error"] = e.Message.ToString();

                UploadUI();

                return View(_context.Profile.ToList());
            }

            UploadUI();

            return View(_context.Profile.ToList());
        }

        [Authorize(Roles = "Admin, user")]
        [HttpPost]
        public async Task<IActionResult> Index(string file, string shipping
            , string fee, string profit, string promoting, string markdown, int items, int min
            , int max, string User)
        {
            try
            {
                var path = Path.Combine(
                       Directory.GetCurrentDirectory(), @"wwwroot\Excel_Source\Shopify_Upload.xlsx");

                Match shippingMatch = Regex.Match(shipping, @"[\d]+");

                Match amazonFee = Regex.Match(fee, @"[\d]+[/.]?[\d]+");

                Match promotingFee = Regex.Match(promoting, @"[\d]+[/.]?[\d]+");

                Match profitMatch = Regex.Match(profit, @"[\d]+");

                Profile oldProfile = _context.Profile.AsNoTracking()
                                        .Where<Profile>(x => x.ProfileUser == User)
                                            .FirstOrDefault();

                Profile profile = new Profile
                {
                    shipping = Double.Parse(shippingMatch.Value),

                    fee = Double.Parse(shippingMatch.Value),

                    profit = Double.Parse(profitMatch.Value),

                    promoting = Double.Parse(promotingFee.Value),

                    ProfileUser = User,

                    items = items,

                    min = min,

                    max = max,

                    html = oldProfile.html,

                    LongstartTitle = oldProfile.LongstartTitle,

                    MidtartTitle = oldProfile.MidtartTitle,

GTI_Solutionx/GTI_Solutionx/Views/Shopify/Delete.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.UsersList>
@{
    ViewBag.Title = "Delete";
}

<div class="wrapper">
    <div class="container-fluid">
        <div class="text-center m-t-15">
            <h2>Shopify Delete</h2>
        </div>

        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="text-center m-t-15">
                            <h3></h3>
                        </div>
                        <p>
                            This application is intended to delete the information from any data from any shopify user.
                        </p>
                        <br />
                        <form asp-controller="Shopify" asp-action="Delete" method="post"
                              enctype="multipart/form-data" style="width: 100%">

                            <div class="form-row">
                                <div class="form-group text-center col-md-6">
                                    <label for="inputUser">User</label>
                                    @Html.DropDownList("User",
                                Model.GroupBy(x => x.userID).Select(m => new SelectListItem() { Text = m.Key }).ToList()
                                , "", new { @class = "form-control", required = "required" })
                                </div>
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control" name="file" value="@ViewBag.ExcelGuid">
                                </div>
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            @if (@ViewData["Error"] != null)
                             {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                            </div>
                            }
                            @if (@ViewData["Success"] != null)
                            {
                            <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-checkbox-marked-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                            </div>
                            }
                            <div class="text-center m-t-15">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-1">
            </div>
        </div>

        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-xl-10">
                <div class="card ">
                    <div class="card-body">
                        <div class="form-group col-md-12">
                            <h2>Shopify Users</h2>
                            <div class="table-responsive">
                                <table id="datatable2" class="table border-0 dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                                    <tr>
                                        <th>User</th>
                                        <th># of Items</th>
                                    </tr>

                                    @foreach (var product in Model.GroupBy(x => x.userID).Select(x => x.FirstOrDefault()))
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => product.userID)
                                            </td>
                                            <td>
                                                @Model.Where(x => x.userID == product.userID).Count()
                                            </td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1">
            </div>
        </div>
    </div>
</div>

GTI_Solutionx/GTI_Solutionx/Views/Shopify/Index.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.UsersList>
@{
    ViewBag.Title = "Download";
}

<div class="wrapper">
    <div class="container-fluid">
        <div class="text-center m-t-15">
            <h2>Shopify Report Download</h2>
        </div>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="text-center m-t-15">
                            <h3></h3>
                        </div>
                        <p>
                            This application is intended to download an excel with all of the
                            users that have uploaded to the database and then be able to upload listings
                            to shopify and then to eBay.
                        </p>
                        <form asp-controller="Shopify" asp-action="Index" method="post"
                              enctype="multipart/form-data" style="width: 100%">

                            <div class="form-row">
                                <div class="form-group text-center col-md-6">
                                    <label for="inputUser">User</label>
                                    @Html.DropDownList("User",
                                                Model.GroupBy(x => x.userID).Select(m => new SelectListItem() { Text = m.Key }).ToList()
                                                , "", new { @class = "form-control", required = "required" })
                                </div>
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control" name="file" value="@ViewBag.ExcelGuid">
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputshipping">Shipping</label>
                                    <input type="text" class="form-control" name="shipping" placeholder="Shipping" value="$6" readonly>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputItems">Items</label>
                                    <input type="number" class="form-control" name="items" placeholder="Items" required>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputFee">eBay Fee</label>
                                    <input type="text" class="form-control" name="fee" value="20%" readonly>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputPromoting">Promoting Listing (Percentage)</label>
                                    <input type="text" class="form-control" name="promoting" placeholder="Promoting Listing" value="10%" readonly>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputProfit">Profit (Percentage)</label>
                                    <input type="text" class="form-control" name="profit" placeholder="Profit" required>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputMarkdown">Markdown (Not a percentage)</label>
                                    <input type="text" class="form-control" name="markdown" placeholder="Markdown">
                                </div>
                                <div class="form-group text-center col-md-12">
                                    <label for="inputPriceRange">Price Range</label>
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputMin">Min</label>
                                    <input type="number" class="form-control" name="min" placeholder="Min">
                                </div>
                                <div class="form-group text-center col-md-6">
                                    <label for="inputMax">Max</label>
                                    <input type="number" class="form-control" name="max" placeholder="Max">
                                </div>
                            </div>
                            <div class="text-center m-t-15">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>
                            @if (@ViewData["Error"] != null)
                             {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                            </div>
                            }
                            @if (@ViewData["Success"] != null)
                            {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                            </div>
                            }
                        </form>
                    </div>
                </div>
            </div>
            <p>
                Last @ViewBag.Wholesalers database update <b>@ViewBag.TimeStamp Updated via  @ViewBag.type</b> <br />
            </p>
            <div class="col-md-12">

            </div>
        </div>
    </div>
</div>

GTI_Solutionx/GTI_Solutionx/Views/Shopify/Update.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.ServiceTimeStamp>
@{
    ViewBag.Title = "Update";
}
<head>
    <!-- DataTables -->
    <link href="~/assets/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
</head>
<div class="wrapper">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card m-b-30">
                    <div class="card-body">
                        <h2>Fragrancex's database One Click update</h2>
                    </div>
                    <div class="card-body">
                        <p>
                            This application is intended to update the
                            GTI Solution's Fragrancex database. Such
                            update includes item price and availability
                            once a day.
                        </p>

                        <form asp-controller="Shopify" asp-action="Update" method="post"
                              enctype="multipart/form-data">
                            <input type="hidden" class="form-control" name="file" value="@ViewBag.ExcelGuid">
                            @if (@ViewData["Error"] != null)
                            {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                            </div>
                            }
                            @if (@ViewData["Info"] != null)
                            {
                            <div class="alert alert-warning alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-alert-circle font-32"></i>@ViewData["Info"]
                            </div>
                            }
                            @if (@ViewData["Success"] != null)
                            {
                            <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-checkbox-marked-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                            </div>
                            }
                            <div class="form-group text-center col-md-12">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th>Last Updated Date</th>
                                        <th>Database Update Type</th>
                                        <th>Wholesaler</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.TimeStamp.ToString("MM/dd/yyyy hh:mm tt")
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.type)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Wholesalers)
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GTI_Solutionx/GTI_Solutionx/Views/Shopify/Upload.cshtml
@model IEnumerable<GTI_Solutionx.Models.Dashboard.Profile>
@{
    ViewBag.Title = "Upload";
}

<head>
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
</head>
<div class="wrapper">
    <div class="container-fluid">
        <div class="text-center m-t-15">
            <h2>Shopify Upload</h2>
        </div>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="card m-b-30">
                    <div class="card-body">
                        <div class="text-center m-t-15">
                            <h3></h3>
                        </div>
                        <p>
                            This application is intended to upload an excel to refresh the database for a particular user.
                        </p>
                        <div id="dropzone">
                            <form asp-controller="Home" asp-action="DropzoneFileUpload" asp-antiforgery="false"
                                  class="dropzone" id="myAwesomeDropzone" enctype="multipart/form-data">
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control" name="fileName" value="@ViewBag.ExcelGuid">
                                </div>
                                <div class="fallback">
                                    Drop files here or click to upload.<br>
                                    <input name="file" type="file" />
                                </div>
                            </form>
                        </div>
                        <br />
                        <form asp-controller="Shopify" asp-action="Upload" method="post"
                              enctype="multipart/form-data" style="width: 100%">

                            <div class="form-row">
                                <div class="form-group text-center col-md-6">
                                    <label for="inputUser">User</label>
                                    @Html.DropDownList("User",
                                               Model.Select(m => new SelectListItem() { Text = m.ProfileUser }).ToList()
                                               , "", new { @class = "form-control", required = "required" })
                                </div>
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control" name="file" value="@ViewBag.ExcelGuid">
                                </div>
                                <div class="text-center m-t-15 invisible">
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            @if (@ViewData["Error"] != null)
                             {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Error"]</strong>
                            </div>
                            }
                            @if (@ViewData["Success"] != null)
                            {
                            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <i class="mdi mdi-close-circle font-32"></i><strong class="pr-1">@ViewData["Success"]</strong>
                            </div>
                            }
                            <div class="text-center m-t-15">
                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <p>
                Last @ViewBag.Wholesalers database update <b>@ViewBag.TimeStamp Updated via  @ViewBag.type</b> <br />
            </p>
            <div class="col-md-1">
            </div>
        </div>
     
    </div>
</div>