GTI_Solutionx/GTI_Solutionx/Controllers/FrogInkController.cs
using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DatabaseModifier;
using ExcelModifier;
using FrgxPublicApiSDK;
using GTI_Solutionx.Code;
using GTI_Solutionx.Data;
using GTI_Solutionx.Models.Dashboard;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GTI_Solutions.Controllers
{
    public class FrogInkController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ApplicationDbContext _context;

        public FrogInkController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }
        
        public IActionResult Index()
        {
            ViewBag.TimeStamp = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().TimeStamp.ToShortDateString();

            ViewBag.type = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().type;

            ViewBag.Wholesalers = _context.ServiceTimeStamp
                .Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault().Wholesalers;

            Guid guid = Guid.NewGuid();

            ViewBag.ExcelGuid = guid.ToString();

            var profile = new Profile();

            return View(_context.Profile.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> ExportToExcel(string file, string shipping
            , string fee, string profit, string promoting, string markdown, int items, int min
            , int max, string User)
        {
            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file + ".xlsx");

            // Update the database once a day
            updateFragrancex();

            Match shippingMatch = Regex.Match(shipping, @"[\d]+");

            Match amazonFee = Regex.Match(fee, @"[\d]+[/.]?[\d]+");

            Match promotingFee = Regex.Match(promoting, @"[\d]+[/.]?[\d]+");

            Match profitMatch = Regex.Match(profit, @"[\d]+");

            Profile oldProfile = _context.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == User).FirstOrDefault();

            Profile profile = new Profile
            {
                shipping = Double.Parse(shippingMatch.Value),

                fee = Double.Parse(amazonFee.Value),

                profit = Double.Parse(profitMatch.Value),

                promoting = Double.Parse(promotingFee.Value),

                ProfileUser = User,

                items = items,

                min = min,

                max = max,

                html = oldProfile.html,

                LongstartTitle = oldProfile.LongstartTitle,

                MidtartTitle = oldProfile.MidtartTitle,

                ShortstartTitle = oldProfile.ShortstartTitle,

                endTtile = oldProfile.endTtile,

                sizeDivider = oldProfile.sizeDivider

            };

            if (markdown != null)
            {
                Match markdownMatch = Regex.Match(markdown, @"[\d]+");
                profile.markdown = Double.Parse(markdownMatch.Value);
            }

            var upc = _context.UPC.ToDictionary(x => x.ItemID, y => y.Upc);

            var prices = _context.Wholesaler_Fragrancex.ToDictionary(x => x.Sku, y => y.WholePriceUSD);

            var descriptions = _context.Wholesaler_Fragrancex.ToDictionary(x => x.Sku, y => y.Description);
            
            FrogInkExcelCreator frogInkExcelCreator = new FrogInkExcelCreator(upc, profile)
            {
                path = path,
                fragrancexPrices = prices,
                descriptions = descriptions
            };

            frogInkExcelCreator.ExcelGenerator();

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }

            memory.Position = 0;

            FileStreamResult returnFile =
                File(memory, Helper.GetContentType(path), profile.ProfileUser
                + "_Converted_" + DateTime.Today.GetDateTimeFormats()[10]
                + Path.GetExtension(path).ToLowerInvariant());

            _context.Profile.Update(profile);

            _context.SaveChanges();

            System.IO.File.Delete(path);

            return returnFile;
        }

        private void updateFragrancex()
        {
            ServiceTimeStamp service = new ServiceTimeStamp();

            if (_context.ServiceTimeStamp.Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault<ServiceTimeStamp>() == null)
            {
                FragancexSQLPreparer(service);
            }
            else if (_context.ServiceTimeStamp.Where(x => x.Wholesalers == Wholesalers.Fragrancex.ToString())
                .LastOrDefault<ServiceTimeStamp>().TimeStamp != DateTime.Today)
            {
                FragancexSQLPreparer(service);
            }
        }

        private void FragancexSQLPreparer(ServiceTimeStamp service)
        {
            var upc = _context.UPC.ToDictionary(x => x.ItemID, y => y.Upc);

            // TODO: Test this functionality once Alex is done with his development!!

            try
            {
                var listingApiClient = new FrgxListingApiClient("346c055aaefd", "a5574c546cbbc9c10509e3c277dd7c7039b24324");

                // For testing purposes

                //List<Product> allProducts = new List<Product>();

                //var product = listingApiClient.GetProductById("412492");

                //allProducts.Add(product);

                var allProducts = listingApiClient.GetAllProducts();

                DBModifierFragrancexAPI dBModifierFragrancexAPI = new DBModifierFragrancexAPI("", upc)
                {
                    allProducts = allProducts
                };

                dBModifierFragrancexAPI.TableExecutor();

                service.TimeStamp = DateTime.Today;

                service.Wholesalers = Wholesalers.Fragrancex.ToString();

                service.type = "API";

                _context.ServiceTimeStamp.Add(service);

                _context.SaveChanges();
            }
            catch (Exception e)
            {

            }
        }
    }
}

GTI_Solutionx/GTI_Solutionx/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GTI_Solutionx.Data;
using GTI_Solutionx.Models.Dashboard;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GTI_Solutions.Controllers
{
    [Authorize(Roles = "Admin, user")]
    public class ProfileController : Controller
    {
        public ApplicationDbContext _context;
        public List<SelectListItem> items = new List<SelectListItem>();

        public ProfileController(ApplicationDbContext context)
        {
            _context = context;

            items.Add(new SelectListItem
            {
                Text = "--Select--",
                Value = "0",
                Selected = true
            });

            items.Add(new SelectListItem
            {
                Text = "For Women/Men",
                Value = "1"
            });

            items.Add(new SelectListItem
            {
                Text = "Perfume/Cologne",
                Value = "2"
            });

            items.Add(new SelectListItem
            {
                Text = "None",
                Value = "3"
            });
        }

        public IActionResult Index()
        {
            ViewBag.CategoryType = items;

            return View(_context.Profile.ToList());
        }

        public IActionResult Title()
        {
            ViewBag.CategoryType = items;

            return View(_context.Profile.ToList());
        }

        public IActionResult Profile(int? page)
        {
            var profiles = _context.Profile.ToList();

            var pageNumber = page ?? 1;

            //var onePageOfProfiles = profiles.ToPagedList(pageNumber, 10);

            //ViewBag.onePageOfProfiles = onePageOfProfiles;

            return View(_context.Profile.ToList());
        }

        [HttpPost]
        public IActionResult ProfileCreator(string userID, string html)
        {
            if(_context.Profile.Any(x => x.ProfileUser == userID))
            {
                Profile profile = new Profile
                {
                    ProfileUser = userID,

                    html = html
                };

                profile.fee = Convert.ToDouble(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.fee).FirstOrDefault());

                profile.items = Convert.ToInt32(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.items).FirstOrDefault());

                try
                {
                    profile.markdown = Convert.ToDouble(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.markdown).FirstOrDefault());
                } catch (Exception e) { };
                
                try
                {
                    profile.LongstartTitle = Convert.ToString(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.LongstartTitle).FirstOrDefault());
                }
                catch (Exception e) { };
                
                try
                {
                    profile.MidtartTitle = Convert.ToString(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.MidtartTitle).FirstOrDefault());
                }
                catch (Exception e) { };
                
                try
                {
                    profile.ShortstartTitle = Convert.ToString(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.ShortstartTitle).FirstOrDefault());
                }
                catch (Exception e) { };
                
                try
                {
                    profile.endTtile = Convert.ToString(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.endTtile).FirstOrDefault());
                }
                catch (Exception e) { };
                
                try
                {
                    profile.sizeDivider = Convert.ToString(_context?.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == userID).Select(y => y.sizeDivider).FirstOrDefault());
                }
                catch (Exception e) { };
                
                _context.Profile.Update(profile);
            }
            else
            {
                Profile profile = new Profile
                {
                    ProfileUser = userID,

                    html = html
                };
                
                _context.Profile.Add(profile);
            }
            
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ProfileUpdator(string User, string html, string longTitle
            , string MidTitle, string shortTitle, string sizeDivider, string endTitle)
        {
            Profile profile = new Profile();

            Profile oldProfile = _context.Profile.AsNoTracking().Where<Profile>(x => x.ProfileUser == User).FirstOrDefault();

            profile.ProfileUser = User;

            profile.html = oldProfile.html;

            profile.items = oldProfile.items;

            profile.markdown = oldProfile.markdown;

            profile.max = oldProfile.max;

            profile.min = oldProfile.min;

            profile.profit = oldProfile.profit;

            profile.promoting = oldProfile.promoting;

            profile.shipping = oldProfile.shipping;

            profile.LongstartTitle = longTitle;

            profile.MidtartTitle = MidTitle;

            profile.ShortstartTitle = shortTitle;

            profile.sizeDivider = sizeDivider;

            profile.endTtile = items.Where(x => x.Value == endTitle).Select(x => x.Text).FirstOrDefault();

            _context.Profile.Update(profile);

            _context.SaveChanges();

            return RedirectToAction("Title");
        }
    }
}

GTI_Solutionx/GTI_Solutionx/Controllers/UpcController.cs
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using DatabaseModifier;
using GTI_Solutionx.Data;
using Microsoft.AspNetCore.Authorization;

namespace GTI_Solutionx.Controllers
{
    public class UpcController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ApplicationDbContext _context;

        public UpcController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Upcs()
        {
            Guid guid = Guid.NewGuid();

            ViewBag.ExcelGuid = guid.ToString();

            return View(_context.UPC.ToList());
        }

        public IActionResult UpcViewer(int? page, string Search_Data)
        {
            var upcs = _context.UPC.ToList();

            var pageNumber = page ?? 1;

            return View();
        }

        [HttpPost]
        public IActionResult UPCImporter(string file)
        {

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file + ".xlsx");

            // Update the DB with the new UPCs

            DBModifierUPC databaseUPC = new DBModifierUPC(path);

            databaseUPC.TableExecutor();

            System.IO.File.Delete(path);

            return RedirectToAction("Upcs");
        }
    }
}

GTI_Solutionx/GTI_Solutionx/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using GTI_Solutionx.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GTI_Solutionx</title>
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">
    <script type="text/javascript" src="/scripts/app.js.gz"></script>
</head>
 
@if (SignInManager.IsSignedIn(User))
{
    var currentUser = await UserManager.GetUserAsync(User);

    var isAdmin = currentUser != null
        && await UserManager.IsInRoleAsync(
            currentUser,
            Users.Admin.ToString());

    var user = await UserManager.GetUserAsync(User);

    var isUser = currentUser != null
        && (await UserManager.IsInRoleAsync(
            currentUser,
            Users.Admin.ToString())
            || await UserManager.IsInRoleAsync(
                currentUser,
                Users.user.ToString()));

    <head>
        <link rel="stylesheet" href="assets/plugins/metro/MetroJs.min.css">
        <link rel="stylesheet" href="assets/plugins/morris/morris.css">
        <link href="assets/plugins/jvectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet">

        @*<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">*@

        <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        @*<link href="~/assets/plugins/animate/animate.css" rel="stylesheet" type="text/css">*@
        <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css">
        <link href="~/assets/css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <header id="topnav">

            <div class="topbar-main">
                <div class="menu-extras topbar-custom">
                    <ul class="list-inline float-right mb-0 ">
                        <li class="list-inline-item dropdown notification-list">
                            <div class="dropdown notification-list nav-pro-img">
                                <a class="dropdown-toggle nav-link arrow-none waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <img src="~/assets/images/users/avatar-1.jpg" alt="user" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5>Welcome!</h5>
                                    </div>
                                    <a asp-area="" class="dropdown-item" asp-controller="Manage" asp-action="ChangePassword"><i class="mdi mdi-account-circle m-r-5"></i>Change Password</a>
                                    <div class="dropdown-divider"></div>
                                    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                                        <button type="submit" class="btn btn-link navbar-btn navbar-link">
                                            <div class="dropdown-item text-danger" href="#"><i class="mdi mdi-power text-danger"></i>Logout</div>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            
            <!-- MENU Start -->
            <div class="navbar-custom">
                <div class="container-fluid">

                    <div id="navigation">
                        <!-- Navigation Menu-->
                        <ul class="navigation-menu">

                            <li class="has-submenu">
                                <a asp-controller="Home" asp-action="Index"><i class="mdi mdi-airplay"></i> @UserManager.GetUserName(User)</a>
                            </li>
                            @if (isUser)
                            {
                            @if (isAdmin)
                            {
                                <li class="has-submenu">
                                    <a href="#"><i class="mdi mdi-gauge"></i>Wholesalers</a>
                                    <ul class="submenu">

                                        <li class="has-submenu">
                                            <a href="#">Fragrancex</a>
                                            <ul class="submenu">
                                                <li><a asp-area="" asp-controller="Shopify" asp-action="Update">API Database Update</a></li>
                                                <li><a asp-area="" asp-controller="Shopify" asp-action="UpdateExcel">Excel DB Update</a></li>
                                                <li><a asp-area="" asp-controller="Upc" asp-action="Upcs">UPC Upload</a></li>
                                            </ul>
                                        </li>

                                        <li class="has-submenu">
                                            <a href="#">AzImporter</a>
                                            <ul class="submenu">
                                                <li><a asp-area="" asp-controller="AzImporter" asp-action="Index">Excel Upload</a></li>
                                                <li><a asp-area="" asp-controller="AzImporter" asp-action="Shipping">Shipping Modifier</a></li>
                                            </ul>
                                        </li>

                                        <li class="has-submenu">
                                            <a href="#">Perfume WorldWide</a>
                                            <ul class="submenu">
                                                <li><a asp-area="" asp-controller="PerfumeWorldWide" asp-action="Index">Excel Comparer</a></li>
                                                <li><a asp-area="" asp-controller="PerfumeWorldWide" asp-action="UpdateExcel">Excel DB Upload</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            }
                            <li class="has-submenu">
                                <a href="#"><i class="mdi mdi-gauge"></i>Inventory Tracker</a>
                                <ul class="submenu">
                                    <li class="has-submenu">
                                        <a href="#">Amazon</a>
                                        <ul class="submenu">
                                            <li><a asp-area="" asp-controller="Amazon" asp-action="Index">Inventory Checker</a></li>
                                            <li><a asp-area="" asp-controller="Amazon" asp-action="Upload">New ASIN</a></li>
                                            <li><a asp-area="" asp-controller="Amazon" asp-action="BlackList">Black List</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-submenu">
                                        <a href="#">Shopify</a>
                                        <ul class="submenu">
                                            <li><a asp-area="" asp-controller="Shopify" asp-action="Index">Download Report</a></li>
                                            <li><a asp-area="" asp-controller="Shopify" asp-action="Upload">Update DB</a></li>
                                            <li><a asp-area="" asp-controller="Shopify" asp-action="Delete">Delete DB</a></li>
                                        </ul>
                                    </li>
                                    <li><a asp-area="" asp-controller="FrogInk" asp-action="Index">Frog Ink</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu">
                                <a href="#"><i class="mdi mdi-gauge"></i>Profile</a>
                                <ul class="submenu">
                                    <li><a asp-area="" asp-controller="Profile" asp-action="Index">Profile Creator</a></li>
                                    <li><a asp-area="" asp-controller="Profile" asp-action="Profile">Profile Viewer</a></li>
                                    <li><a asp-area="" asp-controller="Profile" asp-action="Title">eBay Title Creator</a></li>
                                </ul>
                            </li>
                            }
                            <li class="has-submenu"></li>
                        </ul>
                        <!-- End navigation menu -->
                    </div> <!-- end navigation -->
                </div> <!-- end container -->
             </div> <!-- end navbar-custom -->
        </header>
        
        @RenderBody()
            
        @RenderSection("Scripts", required: false)
        <!-- Footer -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        © 2018 Designed by GTI Solutionx LLC.
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer -->
        <!-- jQuery  -->
        <script src="~/assets/js/jquery.min.js"></script>
        <script src="~/assets/js/popper.min.js"></script>
        <script src="~/assets/js/bootstrap.min.js"></script>
        <script src="~/assets/js/modernizr.min.js"></script>
        <script src="~/assets/js/detect.js"></script>
        <script src="~/assets/js/fastclick.js"></script>
        <script src="~/assets/js/jquery.slimscroll.js"></script>
        <script src="~/assets/js/jquery.blockUI.js"></script>
        <script src="~/assets/js/waves.js"></script>
        <script src="~/assets/js/jquery.nicescroll.js"></script>
        <script src="~/assets/js/jquery.scrollTo.min.js"></script>

        <!-- Required datatable js -->
        <script src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/assets/plugins/datatables/dataTables.bootstrap4.min.js"></script>
        <!-- Buttons examples -->
        <script src="~/assets/plugins/datatables/dataTables.buttons.min.js"></script>
        <script src="~/assets/plugins/datatables/buttons.bootstrap4.min.js"></script>
        <script src="~/assets/plugins/datatables/jszip.min.js"></script>
        <script src="~/assets/plugins/datatables/pdfmake.min.js"></script>
        <script src="~/assets/plugins/datatables/vfs_fonts.js"></script>
        <script src="~/assets/plugins/datatables/buttons.html5.min.js"></script>
        <script src="~/assets/plugins/datatables/buttons.print.min.js"></script>
        <script src="~/assets/plugins/datatables/buttons.colVis.min.js"></script>
        <!-- Responsive examples -->
        <script src="~/assets/plugins/datatables/dataTables.responsive.min.js"></script>
        <script src="~/assets/plugins/datatables/responsive.bootstrap4.min.js"></script>

        <!-- Datatable init js -->
        <script src="~/assets/pages/datatables.init.js"></script>

        <!-- App js -->
        <script src="~/assets/js/app.js"></script>

        <!-- Plugings for the main dashboard-->
        <script src="~/assets/plugins/metro/MetroJs.min.js"></script>
        <script src="~/assets/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script src="~/assets/plugins/sparkline-chart/jquery.sparkline.min.js"></script>
        <script src="~/assets/plugins/morris/morris.min.js"></script>
        <script src="~/assets/plugins/raphael/raphael-min.js"></script>
        <script src="~/assets/pages/dashboard.js"></script>

        <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>

    </body>
}
else
{
    <head>
        <link href="~/assets/plugins/animate/animate.css" rel="stylesheet" type="text/css">
        <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css">
        <link href="~/assets/css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        @RenderBody()

        <hr />

        <!-- Footer -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        © 2018 Designed by GTI Solutionx LLC.
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer -->

        @RenderSection("Scripts", required: false)
    </body>
}
</html>